### ISSUE TITLE
Does not build on FreeBSD 10.3-RELEASE-p4

### ISSUE THREAD

**Issue by shatting** [lovell/farmhash#15]
Runs blazingly fast on my Mac, sadly doesnt build on our production machines.

```
gyp verb get node dir target node version installed: 6.9.2
gyp verb build dir attempting to create "build" dir: /usr/home/username/crawler.live/node_modules/farmhash/build
gyp verb build dir "build" dir needed to be created? /usr/home/username/crawler.live/node_modules/farmhash/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/home/username/crawler.live/node_modules/farmhash/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/home/username/crawler.live/node_modules/farmhash/config.gypi
gyp verb common.gypi checking for gypi file: /usr/home/username/crawler.live/node_modules/farmhash/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/username/crawler.live/node_modules/farmhash/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/username/.node-gyp/6.9.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/username/.node-gyp/6.9.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/home/username/crawler.live/node_modules/farmhash',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/username/.node-gyp/6.9.2
gyp verb `which` succeeded for `gmake` /usr/local/bin/gmake
gyp info spawn gmake
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
gmake: Entering directory '/usr/home/username/crawler.live/node_modules/farmhash/build'
  c++ '-DNODE_GYP_MODULE_NAME=farmhash-legacy' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DFARMHASH_LEGACY' '-DBUILDING_NODE_EXTENSION' -I/home/username/.node-gyp/6.9.2/include/node -I/home/username/.node-gyp/6.9.2/src -I/home/username/.node-gyp/6.9.2/deps/uv/include -I/home/username/.node-gyp/6.9.2/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -fexceptions -Wall -Ofast -flto -funroll-loops -march=native -MMD -MF ./Release/.deps/Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o.d.raw   -c -o Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o ../src/upstream/farmhash-legacy.cc
  c++ '-DNODE_GYP_MODULE_NAME=farmhash-legacy' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DFARMHASH_LEGACY' '-DBUILDING_NODE_EXTENSION' -I/home/username/.node-gyp/6.9.2/include/node -I/home/username/.node-gyp/6.9.2/src -I/home/username/.node-gyp/6.9.2/deps/uv/include -I/home/username/.node-gyp/6.9.2/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -fexceptions -Wall -Ofast -flto -funroll-loops -march=native -MMD -MF ./Release/.deps/Release/obj.target/farmhash-legacy/src/bindings.o.d.raw   -c -o Release/obj.target/farmhash-legacy/src/bindings.o ../src/bindings.cc
  c++ -shared -pthread -rdynamic -m64 -Wl,--export-dynamic  -Wl,-soname=farmhash-legacy.node -o Release/obj.target/farmhash-legacy.node -Wl,--start-group Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o Release/obj.target/farmhash-legacy/src/bindings.o -Wl,--end-group
Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o: file not recognized: File format not recognized
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [farmhash-legacy.target.mk:139: Release/obj.target/farmhash-legacy.node] Error 1
gmake: Leaving directory '/usr/home/username/crawler.live/node_modules/farmhash/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System FreeBSD 10.3-RELEASE-p4
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/username/crawler.live/node_modules/farmhash
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm verb lifecycle farmhash@1.2.1~install: unsafe-perm in lifecycle true
npm verb lifecycle farmhash@1.2.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/home/username/crawler.live/node_modules/farmhash/node_modules/.bin:/usr/home/username/crawler.live/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/username/bin
npm verb lifecycle farmhash@1.2.1~install: CWD: /usr/home/username/crawler.live/node_modules/farmhash
npm info lifecycle farmhash@1.2.1~install: Failed to exec install script
npm verb unlock done using /home/username/.npm/_locks/staging-b2903843cfb30894.lock for /usr/home/username/crawler.live/node_modules/.staging
npm verb stack Error: farmhash@1.2.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid farmhash@1.2.1
npm verb cwd /usr/home/username/crawler.live
npm ERR! FreeBSD 10.3-RELEASE-p4
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "farmhash" "--verbose"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

**Comment by lovell** [comment]
Hello, the salient part of the error message is:

```
Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o: file not recognized: File format not recognized
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Are you using clang or gcc (or another compiler) on FreeBSD?

https://github.com/nodejs/node-gyp/issues/565#issuecomment-97877558 might help.

**Comment by shatting** [comment]
hello!

i am using clang from what i can tell (`clang` is a recognized command, `gcc` isnt). Tried using

`CC=clang CXX=clang++ LINKXX=clang++ LINK=clang npm install farmhash --clang=1`

as suggested in the node-gyp issue, yielding the same result. Usually node-gyp works without any problems on our machines (hiredis,libxmljs,bcrypt,pgbufferutil,lz4,.. off the top of my head). 

I am not very experienced when it comes to compiling c code on unix machines, but my guess would be that some flag is missing or wrong.

**Comment by lovell** [comment]
Thanks for confirming the use of clang. I've experienced problems when using both intrinsics and link time optimisation (LTO) at the same time with clang.

Are you able to try removing the 2x `-flto` flags from the `cflags_cc` sections of [binding.gyp](https://github.com/lovell/farmhash/blob/master/binding.gyp) to see if that works? If so, we can make this a Linux-only flag.

**Comment by lovell** [comment]
@shatting Have you been able to make any progress with this problem?

**Comment by shatting** [comment]
Just tried removing the `-flto` flag in v1.2.1, with both `clang` and `c++`, but no success.

```
Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o: file not recognized: File format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o: file not recognized: File format not recognized
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mylanconnolly** [comment]
I ran into this issue while trying to install webpack-dashboard, and on a whim downloaded a copy of it and ran `npm install` after removing the `-flto` flag and it seemed to build correctly on my machine (running FreeBSD 11.1).

I'm not sure if there is an additional problem related to FreeBSD 10.3, but it seems from my experience that removing the flto flag fixes it with 11.1.

I can send a PR if you'd like but I'm not terribly familiar with node-gyp, so I am not sure how to make it a Linux-only flag.

**Comment by lovell** [comment]
@mylanconnolly Thanks, I made this change in commit 5c9bfb3 on the `master` branch. Are you able to test?

**Comment by mylanconnolly** [comment]
@lovell just cloned from scratch and it works! Thanks!

**Comment by lovell** [comment]
farmhash v2.0.2 now available via npm with this change.

@shatting Are you still experiencing this problem on FreeBSD 10.x?

**Comment by lovell** [comment]
I'll assume this is all OK on FreeBSD now but please feel free to re-open if not. Thanks for everyone's help with feedback and testing.
