### ISSUE TITLE
Error: /User/node_modules/farmhash/build/Release/farmhash.node: invalid ELF header

### ISSUE THREAD

**Issue by yasharma** [lovell/farmhash#21]
I am following this script [node-cluster-socket](https://github.com/elad/node-cluster-socket.io)  and getting this error
```javascript
Error: /User/node_modules/farmhash/build/Release/farmhash.node: invalid ELF header
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/User/node_modules/farmhash/index.js:3:18)
    at Module._compile (module.js:649:30)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .js] (/User/node_modules/babel-register/lib/node.js:152:7)
```
application running in docker container as 
```bash
docker run                  \
    --rm                    \
    --name=xxxx-quiz       \
    --env "APP_HOST=localhost" \
    --env "APP_PORT=8086" \
    --network=xxxx   \
    -v ${PWD}:/xxxx \
    -w "/quiz"  \
    -p 8086:8086            \
    node:9.8.0 \
    npm run dev
```
i even tried to build the container with Dockerfile and then run, however getting the same error

**Comment by lovell** [comment]
Hello, you'll need to run `npm install` on the same platform as used at runtime. (In this example it looks like `npm install` was run on OS X but Debian is being used at runtime.)

**Comment by yasharma** [comment]
@lovell I've tried that as well, running npm install during docker image build, still getting the same error

**Comment by lovell** [comment]
Make sure the `node_modules` directory generated on OS X is not copied into the Linux container.
