### ISSUE TITLE
install fails on node v12.3.1

### ISSUE THREAD

**Issue by japrescott** [lovell/farmhash#25]
build fails on v12.3.1

node-gyp: v3.8.0
node: v12.3.1
npm: 6.9.0

/Edit
This can be fixed when updating the `nan` dependency to `2.14.0`

```
                                                  ^
/root/.node-gyp/12.3.1/include/node/v8config.h:307:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/bindings.cc:16:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)':
../../nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to 'v8::StringObject::New(v8::Local<v8::String>&)'
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /root/.node-gyp/12.3.1/include/node/node.h:63:0,
                 from ../src/bindings.cc:15:
/root/.node-gyp/12.3.1/include/node/v8.h:5380:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^~~
/root/.node-gyp/12.3.1/include/node/v8.h:5380:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/bindings.cc:16:
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/bindings.cc:16:
../../nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before '>' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ')' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from /usr/include/c++/7/cassert:44:0,
                 from /root/.node-gyp/12.3.1/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:55,
                 from ../src/bindings.cc:16:
../../nan/nan_object_wrap.h: In destructor 'virtual Nan::ObjectWrap::~ObjectWrap()':
../../nan/nan_object_wrap.h:24:25: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(persistent().IsNearDeath());
                         ^
../../nan/nan_object_wrap.h: In static member function 'static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)':
../../nan/nan_object_wrap.h:127:26: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(wrap->handle_.IsNearDeath());
                          ^
farmhash.target.mk:120: recipe for target 'Release/obj.target/farmhash/src/bindings.o' failed
make: *** [Release/obj.target/farmhash/src/bindings.o] Error 1
make: Leaving directory '/mystuff/node_modules/farmhash/build'

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v12.3.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/root/.nvm/versions/node/v12.3.1/bin/node" "/root/.nvm/versions/node/v12.3.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mystuff/node_modules/farmhash
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

```

**Comment by lovell** [comment]
The current version range of the `nan` dependency is `^2.10.0` so will include `2.14.0`. Perhaps you need to update lockfile(s) in your `mystuff` directory.

**Comment by japrescott** [comment]
thank you @lovell for the very fast answer. I had already figured it out, that its due to `nan`, but thank you for the hint about package-lock which solved a different error
